apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-selector
  labels:
    app: api-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-selector
  template:
    metadata:
      labels:
        app: api-selector
    spec:
      containers:
      - name: api-selector
        image: api_selector:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
          - name: CHROMA_SERVER_HOST
            value: "chromadb"  # Assuming the service name in the cluster is chromadb
          - name: CHROMA_SERVER_HTTP_PORT
            value: "8000"  # Replace with the actual port if different
          - name: BEARER_TOKEN
            valueFrom:
              secretKeyRef:
                name: chromadb-auth  # The name of your secret
                key: token  # The key within the secret where the token is stored
