# Original Dockerfile: https://github.com/chroma-core/chroma/blob/main/Dockerfile
FROM chromadb/chroma:latest

# Install dependencies required for your script (if they're not already in the base image)
RUN pip install joblib pandas chromadb-client

# Install netcat for the custom entrypoint
RUN apt-get update && apt-get install -y curl

# Set the working directory in the container
WORKDIR /chroma

# Copy the initialization script and the custom entrypoint into the container
COPY embeddings.joblib /chroma/embeddings.joblib
COPY vector_store.py /chroma/vector_store.py
COPY custom_entrypoint.sh /chroma/custom_entrypoint.sh

# Make the custom entrypoint executable
RUN chmod +x /chroma/custom_entrypoint.sh
# docker  
# Use the custom entrypoint
ENTRYPOINT ["/chroma/custom_entrypoint.sh"]
