apiVersion: batch/v1
kind: Job
metadata:
  name: br2-classifier-downloader
  labels:
    app: classifier-downloader
spec:
  template:
    metadata:
      labels:
        app: classifier-downloader
    spec:
      containers:
      - name: classifier-downloader
        image: ghcr.io/superjeffcplusplus/downloader:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: doc-classifier-env
        volumeMounts:
          - name: aws-credentials
            mountPath: /secrets/.aws
          - name: ls-api-token
            mountPath: /secrets/.lstudio
          - name: msebr2-doc-classifier
            mountPath: /app/data
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials
        - name: ls-api-token
          secret:
            secretName: ls-api-token
        - name: msebr2-doc-classifier
          persistentVolumeClaim:
            claimName: msebr2-doc-classifier
  backoffLimit: 4