apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
      - name: chromadb
        image: chroma-db
        ports:
        - containerPort: 8000  # Adjust the port to match ChroMaDB's port
        imagePullPolicy: IfNotPresent
