apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
spec:
  selector:
    app: chromadb
  ports:
  - protocol: TCP
    port: 8000  # Adjust the port to match ChroMaDB's port
    targetPort: 420
