apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-ui
  labels:
    app: telegram-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-ui
  template:
    metadata:
      labels:
        app: telegram-ui
    spec:
      containers:
      - name: telegram-ui
        image: telegram_ui:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
          # ~~~ TELEGRAM ~~~
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-bot-token-notifier
                key: token
