name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get changes
        run: git diff --name-only -r HEAD^1 HEAD

      - name: Build and Push Docker Images
        run: |
          # Add your Docker build and push commands here
          echo "Building and pushing Docker images..."
        if: steps.changed-files.outputs.changed == 'true'
