name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    #env:
    #  REGISTRY_URL: ${{ secrets.GITLAB_REGISTRY_URL }}
    #  USERNAME: ${{ secrets.GITLAB_USERNAME }}
    #  PASSWORD: ${{ secrets.GITLAB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #- name: Log in to GitLab Container Registry
      #  run: echo $PASSWORD | docker login $REGISTRY_URL -u $USERNAME --password-stdin

      - name: Determine changed files
        id: changes
        run: |
          git fetch origin main
          git diff --name-only origin/main | grep 'dockerfile' | tee changed_files.txt

      - name: Build and Push Docker Images
        if: success() && steps.changes.outputs.files
        run: |
          while IFS= read -r file; do
            SERVICE=$(echo $file | cut -d'/' -f2)
      #      IMAGE_NAME=$REGISTRY_URL/your-namespace/$SERVICE:latest
            IMAGE_NAME=$REGISTRY_URL/your-namespace/$SERVICE:latest
            docker build -t $IMAGE_NAME -f $file $(dirname $file)
      #      docker push $IMAGE_NAME
          done < changed_files.txt
