name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get changes
        id: get-changes
        run: |
          CHANGED_FILES=$(git diff --name-only -r HEAD^1 HEAD)
          echo "$CHANGED_FILES" > changed_files.txt
          echo "CHANGED_FILES=$CHANGED_FILES" >> .env

      - name: Check for dockerfile changed files
        id: check-dockerfiles
        run: |
          # Source the .env file to load environment variables
          set -o allexport
          source .env
          set +o allexport
          DOCKERFILES=$(echo "$CHANGED_FILES" | grep -i 'dockerfile' || true)
          if [ -z "$DOCKERFILES" ]; then
            echo "No Dockerfile changes detected."
            exit 0
          fi
          echo "Dockerfile changes detected:"
          echo "$DOCKERFILES"
          echo "DOCKERFILES=$DOCKERFILES" >> .env
          echo "dockerfiles=$DOCKERFILES" >> $GITHUB_ENV

      - name: Save .env to GitHub secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.forge.hefr.ch
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        if: steps.check-dockerfiles.outputs.dockerfiles != ''
        run: |
          for DOCKERFILE in ${{ steps.check-dockerfiles.outputs.dockerfiles }}; do
            IMAGE_NAME=$(dirname $DOCKERFILE | tr / -)
            IMAGE_TAG="registry.forge.hefr.ch/${{ secrets.DOCKER_PASSWORD }}/mse-ai-market-place/${IMAGE_NAME}:latest"
            echo "Building and pushing $IMAGE_TAG"
            docker buildx build --push -t $IMAGE_TAG -f $DOCKERFILE .
          done
