name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get changes
        run: git diff --name-only -r HEAD^1 HEAD

      - name: Check for dockerfile changed files
        run: |
          CHANGED_FILES=$(git diff --name-only -r HEAD^1 HEAD)
          echo "$CHANGED_FILES" > changed_files.txt
          if grep -q 'ockerfile' changed_files.txt; then
            echo "Found a file containing 'ockerfile'."
            echo "Paths of changed files:"
            grep 'ockerfile' changed_files.txt
          else
            echo "No file containing 'ockerfile' found."
          fi
