name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get changes & check for Dockerfile changes
        id: get-changes
        run: |
          CHANGED_FILES=$(git diff --name-only -r HEAD^1 HEAD)
          echo "$CHANGED_FILES" > changed_files.txt
          if grep -q 'ockerfile' changed_files.txt; then
            echo "Dockerfile changes detected:"
            grep 'ockerfile' changed_files.txt
            DOCKERFILES=$(grep 'ockerfile' changed_files.txt)
            echo "DOCKERFILES=$(echo $DOCKERFILES)" >> $GITHUB_ENV
          else
            echo "No Dockerfile changes detected."
            exit 0
          fi
          
      - name: Save .env to GitHub secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.forge.hefr.ch
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          if [ -n "${{ env.DOCKERFILES }}" ]; then
            for DOCKERFILE in ${{ steps.check-dockerfiles.outputs.dockerfiles }}; do
              IMAGE_NAME=$(dirname $DOCKERFILE | tr / -)
              IMAGE_TAG="registry.forge.hefr.ch/${{ secrets.DOCKER_PASSWORD }}/mse-ai-market-place/${IMAGE_NAME}:latest"
              echo "Building and pushing $IMAGE_TAG"
              docker buildx build --push -t $IMAGE_TAG -f $DOCKERFILE .
            done
          else 
            echo "No Dockerfile changes detected."
          fi
