apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-selector
  labels:
    app: api-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-selector
  template:
    metadata:
      labels:
        app: api-selector
    spec:
      containers:
      - name: api-selector
        image: registry.forge.hefr.ch/samuli.lehtinen/mse-ai-market-place/api-selector:latest # api_selector:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
          # ~~~ CHROMA ~~~
          - name: CHROMA_SERVER_HOST
            value: "chromadb"  # Assuming the service name in the cluster is chromadb
          - name: CHROMA_SERVER_HTTP_PORT
            value: "8000"
          - name: CHROMA_BEARER_TOKEN
            valueFrom:
              secretKeyRef:
                name: chromadb-auth  # The name of your secret
                key: token  # The key within the secret where the token is stored
          # ~~~ REDIS ~~~
          - name: REDIS_SERVER_HOST
            value: "redisdb-master"
          - name: REDIS_SERVER_HTTP_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redisdb
                key: redis-password
      imagePullSecrets:
      - name: my-rancher-pwd
